### ISSUE TITLE
Does it mean that we need to train classifiers for many layers (such as layers 20-28)?

### ISSUE THREAD

**Issue by waltonfuture** [zjunlp/Deco#1]
Thanks for your interesting work! When using Deco, do we need to train additional classifiers for proceeding layers besides the last layer? Thank you!

**Comment by sunnychenxiwang** [comment]
> Thanks for your interesting work! When using Deco, do we need to train additional classifiers for proceeding layers besides the last layer? Thank you!
Thank you for your attention in our work.

1. In the probe experiments, we train classifiers at the last position of each layer and find that the classifiers from the preceding layers performed best.
2.  When using Deco in practice, based on finding 2, we simply calculate the layer corresponding to the token with the highest probability among the candidate tokens as the selected layer. We don't need to train additional classifiers.

**Comment by waltonfuture** [comment]
> > Thanks for your interesting work! When using Deco, do we need to train additional classifiers for proceeding layers besides the last layer? Thank you!
> > Thank you for your attention in our work.
> 
> 1. In the probe experiments, we train classifiers at the last position of each layer and find that the classifiers from the preceding layers performed best.
> 2. When using Deco in practice, based on finding 2, we simply calculate the layer corresponding to the token with the highest probability among the candidate tokens as the selected layer. We don't need to train additional classifiers.

Thanks for your response. So, does it mean that we use the same classifier ($\phi$) for the anchor layer as the last layer?

**Comment by sunnychenxiwang** [comment]
> Thanks for your response. So, does it mean that we use the same classifier (
> 𝜙
> ) for the anchor layer as the last layer?

Refering to early exit techniques, we utilize the llm_head to obtain the probability of tokens.

**Comment by zxlzr** [comment]
hi, do you have any further questions?

**Comment by waltonfuture** [comment]
Thanks for your response. I’m a little confused that why we can use lm head on different layers since it is trained for the last layer.

**Comment by sunnychenxiwang** [comment]
> Thanks for your response. I’m a little confused that why we can use lm head on different layers since it is trained for the last layer.

The specific principles can be referenced in relevant papers on early exit techniques, such as:
1. Branchynet: Fast inference via early exiting from deep neural networks
2. Depth-adaptive transformer.
3. Confident adaptive language modeling.

**Comment by zxlzr** [comment]
hi, do you have any further questions?

**Comment by waltonfuture** [comment]
Thank you. I have no more questions.
