### ISSUE TITLE
model.generate problem

### ISSUE THREAD

**Issue by OliverLeeXZ** [zjunlp/Deco#2]
Thanks for your great work! When i use the inference code from TL DR,
    with torch.no_grad():
        output_dict = model.generate(
            input_ids,
            images=images_tensor,
            do_sample=args.do_sample,
            temperature=args.temperature,
            top_p=args.top_p,
            num_beams=args.num_beams,
            max_new_tokens=args.max_new_tokens,
            return_dict_in_generate=True,
            output_hidden_states=True,
            use_deco = True,
            alpha = 0.6,
            threshold_top_p = 0.9, 
            threshold_top_k = 20,
            early_exit_layers=[i for i in range(20, 29)]
            )
                
    output_ids = output_dict.sequences
    outputs = tokenizer.batch_decode(output_ids)
    print(outputs)
 i encountering such problem:    do_sample=args.do_sample,
AttributeError: 'Namespace' object has no attribute 'do_sample'
How can i solve this?

**Comment by sunnychenxiwang** [comment]
It seems that the argparse module does not define the do_sample parameter. You can add parser.add_argument("--do_sample", type=str2bool, default=True) or consider using an alternative approach: 'do_sample=True if args.temperature>0 else False'.

**Comment by OliverLeeXZ** [comment]
Thanks for your rapid response!
