### ISSUE TITLE
tokenizer.batch_decode problem

### ISSUE THREAD

**Issue by OliverLeeXZ** [zjunlp/Deco#3]
Thanks for your interesting work! When I use deco facing such question:
   This line: outputs = tokenizer.batch_decode(output_ids,skip_special_tokens=True)
   
      File "/home/lxz/CODE/hallucination/Deco/test.py", line 180, in <module>
    eval_model(args)
  File "/home/lxz/CODE/hallucination/Deco/test.py", line 162, in eval_model
    outputs = tokenizer.batch_decode(output_ids,skip_special_tokens=True)
  File "/home/lxz/CODE/hallucination/Deco/transformers/tokenization_utils_base.py", line 3485, in batch_decode
    return [
  File "/home/lxz/CODE/hallucination/Deco/transformers/tokenization_utils_base.py", line 3486, in <listcomp>
    self.decode(
  File "/home/lxz/CODE/hallucination/Deco/transformers/tokenization_utils_base.py", line 3525, in decode
    return self._decode(
  File "/home/lxz/CODE/hallucination/Deco/transformers/tokenization_utils.py", line 931, in _decode
    filtered_tokens = self.convert_ids_to_tokens(token_ids, skip_special_tokens=skip_special_tokens)
  File "/home/lxz/CODE/hallucination/Deco/transformers/tokenization_utils.py", line 912, in convert_ids_to_tokens
    tokens.append(self._convert_id_to_token(index))
  File "/home/lxz/CODE/hallucination/Deco/transformers/models/llama/tokenization_llama.py", line 204, in _convert_id_to_token
    token = self.sp_model.IdToPiece(index)
  File "/home/lxz/miniconda3/envs/deco/lib/python3.9/site-packages/sentencepiece/__init__.py", line 1179, in _batched_func
    return _func(self, arg)
  File "/home/lxz/miniconda3/envs/deco/lib/python3.9/site-packages/sentencepiece/__init__.py", line 1172, in _func
    raise IndexError('piece id is out of range.')
IndexError: piece id is out of range.

**Comment by OliverLeeXZ** [comment]
import argparse
import torch

from llava.constants import (
    IMAGE_TOKEN_INDEX,
    DEFAULT_IMAGE_TOKEN,
    DEFAULT_IM_START_TOKEN,
    DEFAULT_IM_END_TOKEN,
    IMAGE_PLACEHOLDER,
)
from llava.conversation import conv_templates, SeparatorStyle
from llava.model.builder import load_pretrained_model
from llava.utils import disable_torch_init
from llava.mm_utils import (
    process_images,
    tokenizer_image_token,
    get_model_name_from_path,
    KeywordsStoppingCriteria,
)

from PIL import Image

import requests
from PIL import Image
from io import BytesIO
import re


def image_parser(args):
    out = args.image_file.split(args.sep)
    return out


def load_image(image_file):
    if image_file.startswith("http") or image_file.startswith("https"):
        response = requests.get(image_file)
        image = Image.open(BytesIO(response.content)).convert("RGB")
    else:
        image = Image.open(image_file).convert("RGB")
    return image


def load_images(image_files):
    out = []
    for image_file in image_files:
        image = load_image(image_file)
        out.append(image)
    return out


def eval_model(args):
    # Model
    disable_torch_init()

    model_name = get_model_name_from_path(args.model_path)
    tokenizer, model, image_processor, context_len = load_pretrained_model(
        args.model_path, args.model_base, model_name
    )

    qs = args.query
    image_token_se = DEFAULT_IM_START_TOKEN + DEFAULT_IMAGE_TOKEN + DEFAULT_IM_END_TOKEN
    if IMAGE_PLACEHOLDER in qs:
        if model.config.mm_use_im_start_end:
            qs = re.sub(IMAGE_PLACEHOLDER, image_token_se, qs)
        else:
            qs = re.sub(IMAGE_PLACEHOLDER, DEFAULT_IMAGE_TOKEN, qs)
    else:
        if model.config.mm_use_im_start_end:
            qs = image_token_se + "\n" + qs
        else:
            qs = DEFAULT_IMAGE_TOKEN + "\n" + qs

    if "llama-2" in model_name.lower():
        conv_mode = "llava_llama_2"
    elif "v1" in model_name.lower():
        conv_mode = "llava_v1"
    elif "mpt" in model_name.lower():
        conv_mode = "mpt"
    else:
        conv_mode = "llava_v0"

    if args.conv_mode is not None and conv_mode != args.conv_mode:
        print(
            "[WARNING] the auto inferred conversation mode is {}, while `--conv-mode` is {}, using {}".format(
                conv_mode, args.conv_mode, args.conv_mode
            )
        )
    else:
        args.conv_mode = conv_mode

    conv = conv_templates[args.conv_mode].copy()
    conv.append_message(conv.roles[0], qs)
    conv.append_message(conv.roles[1], None)
    prompt = conv.get_prompt()

    image_files = image_parser(args)
    images = load_images(image_files)
    images_tensor = process_images(
        images,
        image_processor,
        model.config
    ).to(model.device, dtype=torch.float16)

    input_ids = (
        tokenizer_image_token(prompt, tokenizer, IMAGE_TOKEN_INDEX, return_tensors="pt")
        .unsqueeze(0)
        .cuda()
    )

    stop_str = conv.sep if conv.sep_style != SeparatorStyle.TWO else conv.sep2
    keywords = [stop_str]
    stopping_criteria = KeywordsStoppingCriteria(keywords, tokenizer, input_ids)
    with torch.no_grad():
        output_dict = model.generate(
            input_ids,
            images=images_tensor,
            do_sample=True if args.temperature > 0 else False,
            temperature=args.temperature,
            top_p=args.top_p,
            num_beams=args.num_beams,
            max_new_tokens=args.max_new_tokens,
            return_dict_in_generate=True,
            output_hidden_states=True,
            use_deco = True,
            alpha = 0.6,
            threshold_top_p = 0.9, 
            threshold_top_k = 20,
            early_exit_layers=[i for i in range(20, 29)]
            )
                
    output_ids = output_dict.sequences
    outputs = tokenizer.batch_decode(output_ids,skip_special_tokens=True)
    print(outputs)

**Comment by sunnychenxiwang** [comment]
In LLaVA, the special token <image> is assigned an ID of -200, which the tokenizer cannot properly process. Therefore, the code needs to be modified as follows:
outputs = tokenizer.batch_decode(output_ids[:,input_ids.size(1):],skip_special_tokens=True)

**Comment by OliverLeeXZ** [comment]
Thanks for your rapid response!
