### ISSUE TITLE
Regarding the cases of Qwen-VL in Figure 11

### ISSUE THREAD

**Issue by shikiw** [zjunlp/Deco#4]
Hi, thanks for the impressive work! The solution of Deco is really interesting and inspiring.

I notice that, in Figure 11 of the paper, the cases show the quite long captions generated by Qwen-VL on the given images. But in my implementation, Qwen-VL can just generate relatively short captions if I use "Describe this image in detail." as the prompt. Could you please tell me if I miss some important details? Any information about either model types or implementation details will be greatly appreciated!

**Comment by sunnychenxiwang** [comment]
Thank you for your attention! We are using the Qwen-VL-chat (sft) version. We suspect that the Qwen-VL you are using outputs shorter captions for image captioning.

**Comment by zxlzr** [comment]
hi, do you have any further questions?

**Comment by shikiw** [comment]
@sunnychenxiwang @zxlzr  Thanks for the quick reply! Actually I have also tried on Qwen-VL-Chat via the generation script provided  in their official huggingface https://huggingface.co/Qwen/Qwen-VL-Chat, but still obtaining not so long captions. Could you please kindly provide the part of code you used for Qwen-VL-Chat generation?

**Comment by sunnychenxiwang** [comment]
I am sorry for not explaining clearly. During our experiment, we found that using the prompt 'Describe this image in detail' generated shorter responses from Qwen-VL-chat. Later, we adjusted the prompt to 'Please describe this image in detail' and ensured that a consistent prompt was used throughout the Qwen-VL-chat experiments.

**Comment by sunnychenxiwang** [comment]
I am sorry for not explaining clearly. During our experiment, we found that using the prompt 'Describe this image in detail' resulted in shorter responses from Qwen-VL-chat. We later adjusted the prompt to 'Please describe this image in detail' and ensured that a consistent prompt was used throughout the Qwen-VL-chat experiments. If you would like to communicate further, you can add me on WeChat at sunny_wcx_

**Comment by shikiw** [comment]
Thanks for your detailed reply! It helps a lot!
